---
apiVersion: v1
kind: Service
metadata:
  labels:
    expose: "true"
    app: event
    provider: fabric8
    version: "latest"
  name: eventservice
spec:
  ports:
  - name: eventport
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: event
    provider: fabric8
