#H2 settings ${port:8080}
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: toregard
#    thymeleaf:
#      cache: false
#      enabled: true
#      prefix: classpath:/templates/
#      suffix: .html

#server:
#  port: 8080
#  error:
#    path: /error
#    whitelabel:
#      enabled: false
