apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: event
  name: eventbuild
  namespace: myproject
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'event-sourcing-cqrs-axon-spring-boot:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: 'https://github.com/toretest/event-sourcing-cqrs-axon-spring-boot.git'
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 's2i-java:latest'
    type: Source


