apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: event
  name: eventsourcing
  namespace: myproject
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: 'eventsourcing:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: DockerImage
          name: 'fabric8/s2i-java:latest'
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers: []



