apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: eventsourcing-buildcconfig-s2i
  labels:
    app: eventsourcing
  namespace: myproject
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'eventsourcing:0.3'
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: 'fabric8/s2i-java:2.3'
    type: Source
  successfulBuildsHistoryLimit: 5
